vars:
  - key: POSTGRES_DB
    default: hotel_db

services:
  - type: web
    name: hotel-management-server
    env: docker
    dockerContext: server
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ${POSTGRES_DB}
          property: connectionString
      - key: POSTGRES_DB
        fromDatabase:
          name: ${POSTGRES_DB}
          property: database
      - key: JWT_SECRET
        generateValue: true
      - key: ${GROQ_API_KEY}
        sync: false
      - key: PORT
        value: 4000

databases:
  - name: ${POSTGRES_DB}
    plan: free
