services:
  - type: web
    name: hotel-server
    env: docker
    rootDir: server
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hotel_db
          property: connectionString
      - key: POSTGRES_DB
        fromDatabase:
          name: hotel_db
          property: database
      - key: JWT_SECRET
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
      - key: PORT
        value: 4000

databases:
  - name: hotel_db
    plan: free